### ISSUE TITLE
App#Domain#Edit

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#112]
There's an 'edit' link on a vhost (domain) show page, but no route/template for editing yet.

 - [x] Edit page updates title to "Edit ${domain.virtual_domain} - ${app.handle}" (from #94)

  - [x] style to match other pages
  - [x] create "reprovision" operation after editing

@sandersonet Any important difference between an "add domain" page (shown below) and an "edit domain" page? Anything that should not be changeable when editing an existing domain?

![image](https://cloud.githubusercontent.com/assets/2023/6308407/2ba7e1bc-b912-11e4-9bc1-0dda004fabf9.png)

**Comment by sandersonet** [comment]
@bantic great question.

The UI should be the same as new with the following exceptions:

* Service should not be changeable.  Populate the dropdown the the selected service and disable it.
* Virtual domain should be populated with the existing virtual domain.
* Change the panel title to "Edit ${virtual_domain}"

Certificate and private key should be blank.

When editing a domain, you'll have to do a couple things to save correctly.

1) Save the actual vhost to persist any changes to virtual domain
2) Create a new reprovision operation with the new cert/private key pair

Let myself or @fancyremarker know if you have any questions about how this works.

**Comment by bantic** [comment]
@sandersonet Do we need to create a "provision" operation when we first create the vhost (at /apps/:id/vhosts/new) then, too? The vhost#new route only POSTs to create the vhost but does not create any `operation` at the same time.

**Comment by sandersonet** [comment]
Yep, you'll need a provision operation when creating a new vhost.
