### ISSUE TITLE
Unverified account view (screen 201)

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#128]
from #51 
  
  * [x] Don't block entire UX for unverified users.  Provide glimpse of provisioned account and any "apps" they provisioned in set up flow.
  * ~~[ ] Create the apps/databases but do not provision. Upon verification of a user, provision any apps/dbs they have not provisioned.~~ (already happens as of https://github.com/aptible/diesel.aptible.com/commit/2d1f2aefeaa7d512b379eb4a6f9f4ce0dbb678d6)
  * [x] verify that deploys check for a verified user.
     * Unverified users are prevented from creating operations in https://github.com/aptible/api.aptible.com/pull/168
  * [x] unverified users see a verify page (needs design for apps/dbs they have created)
  * [x] unverified users see a verify message with button to click to resend verification email

**Comment by bantic** [comment]
@sandersonet Is this one still blocked on a new design?

**Comment by sandersonet** [comment]
@bantic I'm still working on design, but I don't think it needs to block you.  For now, you can use screen 201 and 202 for inspiration.  Namely, we if you can show that the user is not verified and have a call to action to resend the email.

**Comment by bantic** [comment]
@sandersonet excellent! thanks, will do

**Comment by bantic** [comment]
Steps to re-send a verification email for a user:
  * In dashboard, we use the [verification_code_reset_url](https://github.com/aptible/aptible-rails/blob/3bebcb97e4d61eb829edb96e32b9ce6ec3fba612/lib/aptible/rails/view_helper.rb#L21), which resolves to an auth url at `'/reset'`
  * Diesel must create a new `reset` object of type `'verification_code'`, POSTing it to auth to create it
  * Auth will handle updating the verification reset code for the user

**Comment by bantic** [comment]
The "unverified banner" looks like:

![image](https://cloud.githubusercontent.com/assets/2023/6360774/aefeb92e-bc4a-11e4-8fa2-0a176aacb329.png)

**Comment by bantic** [comment]
unverified banner looks like this:

![image](https://cloud.githubusercontent.com/assets/2023/6360845/4e791d78-bc4b-11e4-919c-49f721201f84.png)

**Comment by bantic** [comment]
A walk-through of what an unverified user sees after finishing signing up:

![unverified](https://cloud.githubusercontent.com/assets/2023/6360852/5c11b51c-bc4b-11e4-95e1-4b9d70512a2e.gif)

@sandersonet I'm thinking the following things need to change for the unverified user:

  * [ ] do not show "create app" button
  * [ ] do not show "create database" button
  * [ ] Show a "you must be verified" message instead of a form at apps/new, databases/new and logging/new (the user will get redirected automatically to logging/new when they click the "logging" tab)

Can you let me know if that looks correct or if I'm missing anything?

**Comment by sandersonet** [comment]
You are absolutely correct @bantic

**Comment by bantic** [comment]
Visiting apps/new as an unverified user now shows this:

![image](https://cloud.githubusercontent.com/assets/2023/6375886/2ab9ea32-bce8-11e4-8522-9af852d7eba9.png)

**Comment by bantic** [comment]
visiting dbs/new while unverified now shows this:

![image](https://cloud.githubusercontent.com/assets/2023/6375984/cc43db56-bce8-11e4-9da6-9355a6b6303e.png)

**Comment by bantic** [comment]
logging/new while unverified now show this:

![image](https://cloud.githubusercontent.com/assets/2023/6376095/ba5600f8-bce9-11e4-9d83-ca6048d44fbc.png)

**Comment by sandersonet** [comment]
:+1:
