### ISSUE TITLE
Validate uniqueness in signup flow

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#131]
We should guarantee uniqueness of the following fields during signup flow.  Ideally this validation can happen in context and should prevent a user from `Next`ing until they are addressed.
- [x] User email
- [x] Stack handle
- [x] App handle
- [x] DB handle

also

- [ ] Organization name (or handle) in #44

E.g.: 
![screenshot 2015-02-25 14 00 59](https://cloud.githubusercontent.com/assets/884151/6378092/d99f4386-bcf6-11e4-859e-a8fba67200b2.png)

Currently we don't catch stack, app, or DB validation errors until the payment method step, which is confusing.

**Comment by mixonic** [comment]
We've been using the https://github.com/dockyard/ember-validations project for validations. It has support for "remote" validations that should allow for uniqueness checks.

**Comment by sandersonet** [comment]
FYI @mixonic @bantic I bumped this to Erin go bragh

**Comment by bantic** [comment]
@sandersonet great. If you are not actively working on this I'll take it.

**Comment by sandersonet** [comment]
I'm not, it's all yours!  :smiley:

**Comment by bantic** [comment]
sweet...nabbin' it

**Comment by bantic** [comment]
unassigning myself for now — will revisit this after finishing up organizations work #188

**Comment by sandersonet** [comment]
Fixed by https://github.com/aptible/diesel.aptible.com/pull/270
