### ISSUE TITLE
App creation flow

### ISSUE THREAD

**Issue by chasballew** [aptible/diesel.aptible.com#145]
Hey guys, when I create a new app, I get sent back to /stacks/[:stack_id]/apps. Do you think I should I be redirected to the new app's /services view, with instructions for adding the appropriate git remote?

I feel like I should see this view: 
![screenshot 2015-02-26 00 57 25](https://cloud.githubusercontent.com/assets/3422584/6387061/7ff238b4-bd52-11e4-9fbd-f8f1c0fd84ac.png)

...with simple instructions for getting this app's git setup working.

**Comment by bantic** [comment]
@chas would it make sense if we automatically directed the user to the /apps/:id/deploy page for that newly-created app? it looks like this:

![image](https://cloud.githubusercontent.com/assets/2023/6677784/9dbb9604-cc09-11e4-8b68-fe0f310d52d0.png)

**Comment by chasballew** [comment]
Looks good. If they have an SSH key loaded, it should just give them a click-to-copy remote.
