### ISSUE TITLE
"cancel" button for new app doesn't always work

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#165]
If you go to a stack that has no apps you will be redirect to stacks/:id/apps/new, and the "cancel" button on this template is a no-op because the default behavior of `cancel` is to redirect you to apps.index...which redirects you again to apps.new when the stack has no apps.

The cancel button should either not be present or have another behavior when the stack has no apps.

@sandersonet Do you have a suggestion? I think I would vote for no "Cancel" button in this case.

**Comment by sandersonet** [comment]
I agree, let's remove the cancel button.  Nice catch, @bantic
