### ISSUE TITLE
Rename the host/port labels in the log drain creation form

### ISSUE THREAD

**Issue by ianyamey** [aptible/diesel.aptible.com#179]
When creating a new log drain, changing the type (eg to 'elasticsearch') does not alter the host/port labels.

![log drain naming of labels](https://cloud.githubusercontent.com/assets/142204/6717702/d6854b16-cd84-11e4-9268-5d1fd08c0113.png)

I'd expect the label text to change to 'Elasticsearch Host' and 'Elasticsearch Port'. Alternatively, you could consider just labelling them generically with 'Host' and 'Port'

**Comment by chasballew** [comment]
Great point, thanks!
