### ISSUE TITLE
aptible-ability needs to check an organization's roles

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#183]
`aptible-ability` currently only accepts a stack as the target object. It needs to be updated to accept an organization or a stack.

**Comment by bantic** [comment]
An org hasMany roles and each role has a boolean `isPrivileged` flag.
The user hasMany roles as well. For every role a user has, this describes whether that role grants read and/or manage permissions to an org.

If any role grants manage, the user can manage. If any role grants read, the user can read.

org.roles includes role  |   role is privileged  |  can read?   |   can manage?
-------------------------------|--------------------------|------------|-------------------------
N | n/a | &times; | &times;
Y | N | &#10004; | &times;
Y | Y | &#10004; | &#10004;

cc @sandersonet do I have that right?

**Comment by sandersonet** [comment]
Correct.

The `:read` and `:manage` permissions apply only to stacks and their child resources, not organizations. 

For organizations and their child resources, `:read` is granted implicitly by membership in the org and `:manage` is granted by membership in an org role with `privileged: true`.
