### ISSUE TITLE
organization settings: pending invitations page

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#190]
refs #188 

Should look like this:

![image](https://cloud.githubusercontent.com/assets/2023/6782934/6c80e01e-d14d-11e4-80ed-5b83e8aa1a64.png)

**Comment by bantic** [comment]
@sandersonet There isn't currently an api endpoint for re-sending an invitation, correct? Is that functionality that exists in the current dashboard?

**Comment by sandersonet** [comment]
There is already an end point and the current dashboard uses it here:
https://github.com/aptible/dashboard.aptible.com/blob/master/app/controllers/invitations_controller.rb#L40
