### ISSUE TITLE
Organization > Environments

### ISSUE THREAD

**Issue by mixonic** [aptible/diesel.aptible.com#201]
Existing screen:

![](https://api.monosnap.com/rpc/file/download?id=HrkMsOZj430guBTmOt4StKBFhU6uJU)

Refs https://github.com/aptible/diesel.aptible.com/issues/188

**Comment by mixonic** [comment]
I'd like to punt on this UI. @sandersonet I believe we're handling pretty much anything a user might want to do on this page elsewhere in the UI. It seems like this page should not be needed, and that if it is we might just improve the interactions with stacks elsewhere.

**Comment by sandersonet** [comment]
For now, you are exactly right.  Sometime very soon, users will need to be able to provision new stacks and at that time, we'll have to revisit design.  Thanks for bringing this up.

**Comment by mixonic** [comment]
Great. Closing this then and punting for this pass.
