### ISSUE TITLE
Custom 404

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#213]
Looks like Divshot is serving up a standard 404.  For now, lets use the existing 404:  https://dashboard.aptible.com/404

**Comment by bantic** [comment]
@sandersonet Do you mean a catchall route for ember to display when it doesn't recognize the route? Right now [divshot is configured](https://github.com/aptible/diesel.aptible.com/blob/master/divshot.production.json#L8) to serve the index.html for any route it doesn't recognize.

**Comment by bantic** [comment]
closed by #218
