### ISSUE TITLE
Missing option to create database/app

### ISSUE THREAD

**Issue by jbergknoff** [aptible/diesel.aptible.com#221]
I'm not seeing an option to create new database/app when one already exists. When none exists, the option to create the first is there. I'm using https://diesel.aptible-staging.com.

**Comment by sandersonet** [comment]
@jbergknoff Thanks a ton for catching this!  

@bantic looks like an issue with `aptible-ability` component not correctly validating stack permissions.   Confirmed on staging and locally.
