### ISSUE TITLE
Organizations > edit permission on a role

### ISSUE THREAD

**Issue by mixonic** [aptible/diesel.aptible.com#225]
In the old UI:

![](https://api.monosnap.com/rpc/file/download?id=CygjH8J7TxIb3fhtyCgeFAllyCfIxS)

The list of checkboxes is implemented as follows:

* Walk all accounts/stacks/environments for this organization
* For each, display the name and:
  * A checkbox for a permission named manage
  * A checkbox for a permission name read
* If a box is checked, this means the permission should be created
* If a box in unchecked, that permission should be destroyed.

refs #188

**Comment by bantic** [comment]
this is now part of the roles/show page and is covered by #239
