### ISSUE TITLE
organization settings > edit user roles (memberships)

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#228]
refs #188

**Comment by bantic** [comment]
@sandersonet How should diesel determine which of a user's roles should be unable to be un-checked? As shown here:

![image](https://cloud.githubusercontent.com/assets/2023/6832988/36b2766e-d300-11e4-86ee-fb80305f04ba.png)

**Comment by sandersonet** [comment]
Good question @bantic 

In the case of your screenshot, if you unchecked that role and hit save, you would effectively remove yourself from the organization.  We need to make sure all users are in at least one role in the organization.

Removal from the organization needs to be an explicit action, not a byproduct of changing someone's role.

**Comment by sandersonet** [comment]
@bantic I describe this in more detail here: https://github.com/aptible/diesel.aptible.com/issues/206#issuecomment-85575345

**Comment by bantic** [comment]
@sandersonet ah, ok, perfect. That makes total sense. Thanks.

**Comment by bantic** [comment]
this in progress on https://github.com/mixonic/diesel.aptible.com/tree/membership
It relies on code from #231

**Comment by bantic** [comment]
closed by #236
