### ISSUE TITLE
Segment/Analytics.js

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#230]
Diesel is currently not tracking page views and customer attributes correctly.

When a user is logged in and behind an authenticated route, we need to identify them with an ID, name and email.

`analytics.identify(user.id, { name: user.name, email: user.email });`

Diesel also should track a page view for each route (authenticated or not).  I think using the title attribute already hooked into our routes would be great.

`analytics.page(page.title);`

More info:
https://segment.com/docs/libraries/analytics.js/#page
https://segment.com/docs/libraries/analytics.js/#identify

**Comment by sandersonet** [comment]
Also important to note that `analytics.page();` will trigger the intercom.io integration so it needs to come **after** we call `analytics.identify()`

**Comment by sandersonet** [comment]
@chasballew Can you mention what other attributes you'd like to see us using to further segment users?

**Comment by chasballew** [comment]
@samyount is going to participate as well

**Comment by sandersonet** [comment]
@mixonic @bantic Forgot to mention this issue on the call earlier.  This issue is also a requirement for launch, if possible.

**Comment by sandersonet** [comment]
Fixed by #267
