### ISSUE TITLE
Use correct Git endpoint

### ISSUE THREAD

**Issue by samyount** [aptible/diesel.aptible.com#232]
![screenshot 2015-03-26 18 22 28](https://cloud.githubusercontent.com/assets/6394440/6858463/3253e1da-d3e5-11e4-9827-6aeb88fbb871.png)

Hangs and fails.  Correct endpoint is beta.aptible.com.

**Comment by chasballew** [comment]
https://github.com/aptible/api.aptible.com/blob/a3aecb9a8139aef6dea7bc4b0577f8e603622f56/app/decorators/app_decorator.rb#L9

This is set dynamically by API with git@aptible.com as the failover. @fancyremarker just added the correct ENV.
