### ISSUE TITLE
org > role > show/edit page

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#239]
possible actions on this page:

  * [x] edit role name
  * [x] toggle "admin" status
  * [x] toggle read/manage permissions for each of the org's stacks
  * [x] add existing member to role
  * [x] invite new user by email to role
  * [x] view current role members, with button for removing
  * [x] view pending invitations, with buttons for resend and remove

![image](https://cloud.githubusercontent.com/assets/2023/6899743/52fa2488-d6d0-11e4-8eba-a7c20ea60f74.png)

**Comment by sandersonet** [comment]
FYI when admin role is checked, we should set Read and Manage to true for all stacks and disable the checkboxes.

**Comment by sandersonet** [comment]
Also, feel free to just use checkboxes for any of those fancy toggle switches for now.

**Comment by bantic** [comment]
@sandersonet great, will do, thanks.

**Comment by mixonic** [comment]
Tackling adding an existing user to a role now, should be pretty straight ahead

**Comment by bantic** [comment]
@mixonic can we check the "add existing member to role" box now?
