### ISSUE TITLE
Unable to accept invitations when not logged in

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#252]
If I do not already have an Aptible account, when I click-through an invitation link, I should be prompted to create a user.  This user should immediately be associated to the invited role and added to the organization, skipping Stack/App/PaymentMethod creation along the way.

Currently what happens is that the claim route immediately redirects unauthenticated users to `signup`, where they start the signup process from scratch and are never actually accepted into the organization.

**Comment by bantic** [comment]
discussed w/ @sandersonet 

The signup screen that the unauthenticated user see should be modified to:

  * not show the input for an organization name
  * mention the name of the organization that the user is invited to
  * mention the name of the inviter

Visual:

![image](https://cloud.githubusercontent.com/assets/2023/6948306/f8a3d14e-d87a-11e4-898d-537bbc9eac48.png)

The user can also click the "sign in instead". Either way (after creating a new user, or signing in as an existing user), the next step is to show the user a page that has a prominent button to "accept the invitation to this organization". It should also mention the name of the org and the inviter name.

A logged-in user would go directly to that "accept invitation" page.
