### ISSUE TITLE
missing `resend-invitation` component/helper

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#261]
![image](https://cloud.githubusercontent.com/assets/2023/6975616/57964af0-d96c-11e4-948f-78f63c4cbac4.png)

The `resend-invitation` component was removed, but it's still referenced in the [invited user partial](https://github.com/aptible/diesel.aptible.com/blob/master/app/templates/organization/-invited-user.hbs#L16).

Need to also change the `resentInvitation` action in [org members index route](https://github.com/aptible/diesel.aptible.com/blob/master/app/organization/members/index/route.js#L23-L26) to resend the invitation (as in the [org roles show route](https://github.com/aptible/diesel.aptible.com/blob/master/app/organization/roles/show/route.js#L99-L106)).

**Comment by sandersonet** [comment]
FYI this is fixed in https://github.com/aptible/diesel.aptible.com/pull/260

**Comment by bantic** [comment]
sweet, thanks
