### ISSUE TITLE
Use roles and permissions to hide/show UI elements

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#42]
Refs #28.

Diesel needs to read the roles for a user and permissions for a stack and use those to determine whether to show certain UI elements like the "create app" and "create database" links.

For the moment it should be sufficient to determine on a per-stack basis whether a user has the "manage" permission or not. The "read" permission is implied by the fact that the API returned the stack at all, and the "manage" permission is the only current permission that is required to be able to create/edit stacks, apps and databases.

See https://github.com/aptible/api.aptible.com/issues/144 for more on permissions and how they will change in the future.

A (probably) incomplete list of places in the UI where elements are conditionally shown based on the manage permission:

  * Apps listing page  ![aptible apps 2015-01-07 11-54-27](https://cloud.githubusercontent.com/assets/2023/5649474/141a8e6c-9664-11e4-8213-604555907f37.jpg)
  * App show page  ![google 2b hangouts 2015-01-07 11-16-06](https://cloud.githubusercontent.com/assets/2023/5649492/588b018a-9664-11e4-809b-a784a507d61b.png)

  * DB Listing page  ![aptible databases 2015-01-07 11-56-02](https://cloud.githubusercontent.com/assets/2023/5649482/32f413d0-9664-11e4-9d63-bfa2cbb3fdd7.jpg)

**Comment by bantic** [comment]
cc @sandersonet and/or @fancyremarker can you take a look at the above and lmk if I missed anything important?

**Comment by sandersonet** [comment]
Looks great.  I believe your screenshots cover all possible scenarios.

On Wed, Jan 7, 2015 at 11:59 AM, Cory Forsyth <notifications@github.com>
wrote:

> cc @sandersonet <https://github.com/sandersonet> and/or @fancyremarker
> <https://github.com/fancyremarker> can you take a look at the above and
> lmk if I missed anything important?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aptible/diesel.aptible.com/issues/42#issuecomment-69052980>
> .
>



-- 
*Skylar Anderson*
https://www.aptible.com

**Comment by fancyremarker** [comment]
Super. How hard is it now to determine a user's capabilities? We can probably afford to encapsulate some of this information in the token itself.

**Comment by sandersonet** [comment]
That could save some HTTP requests.  Right now, the current process is like so:

* Fetch current users roles
* For each stack, fetch stack's permissions
* Determine which permissions the user has on the stack by intersecting `user.roles` with `stack.permission.roles`

If we could embed a user's roles into the token, that would save having to ever fetch roles.  Further, I think we should embed permissions into `stack/:id`.

**Comment by bantic** [comment]
Yeah, that makes sense. We could also embed/sideload the stack's permissions. ember-data *should* make this a pretty seamless process from the front-end's perspective

**Comment by bantic** [comment]
closed by #48
