### ISSUE TITLE
empty app view (screen 203)

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#78]
from #51.

The empty app view screen shows info on how to deploy an app.
Should look like:

![image](https://cloud.githubusercontent.com/assets/2023/5948200/15a6ab36-a711-11e4-8aaf-c910632a5a3e.png)

**Comment by bantic** [comment]
@fancyremarker How would diesel know that an app had been deployed before? Would it be enough to know that app.lastDeployOperation is not empty?

**Comment by fancyremarker** [comment]
If there's no `lastDeployOperation`, then no deploy has been attempted.

If there's no successful deploy operation or, alternatively, no services, then no deploy has been successful.

**Comment by sandersonet** [comment]
@bantic , I've thought about this further and think there is a minor mistake in the design I provided.  Even though the app is technically 'empty', I think there is still some value in a: allowing the user to see app activity, and b: allowing the user to deprovision the empty app.

So, I think we still need an app nav for this screen with 3 tabs: 'Deploy', 'Activity', and 'Deprovision'.  Activity and Deprovision are the same as what we currently have and Deploy is the 3 deploy step UI from the original design.

'Services' and 'Domains' tabs should still be removed from the empty app nav.

**Comment by bantic** [comment]
@sandersonet Makes sense — the "deploy" tab is only there for a not-previously-deployed app, then? And is it the default tab shown for a not-previously-deployed app? Current default is the ["services" tab](https://github.com/aptible/diesel.aptible.com/blob/master/app/app/index/route.js#L5).

I am very nearly finished with an update to the HAL adapter to have it read in the embedded lastOperation and lastDeployOperation for an app. Once that is in this should be a fairly straightforward issue.

**Comment by sandersonet** [comment]
Yep, exactly.

**Comment by bantic** [comment]
@sandersonet Any objection to modifying the API to include this as a property of the app. Like `last_successful_deploy_at` or embedding another `last_successful_deploy_operation` operation object? It would simplify the checking we'd otherwise need to do when we enter the app show page.

**Comment by sandersonet** [comment]
I think embedding `last_successful_deploy_operation` sounds like a good fit.  Feel free to add this to API yourself, or I can handle it later this afternoon.

**Comment by fancyremarker** [comment]
:+1: , SGTM.

Also, if it's easier, we can add a `status` field to `App` and set it to `provisioned` (or some other value) in Sweetness once a successful deploy happens.

**Comment by bantic** [comment]
@fancyremarker that would be the simplest. Would that be straightforward for me to add to the API? Else I can embed a `last_successful_deploy_operation` easily. Either way will make an API pr soon...
