### ISSUE TITLE
app show page

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#86]
from #51 

Show last deploy and current git ref on app show page.

![image](https://cloud.githubusercontent.com/assets/2023/6218881/fdfb8896-b5f0-11e4-9de4-e1f0a41596a7.png)

**Comment by sandersonet** [comment]
@bantic, we actually don't have a Users#show page yet, so the user's name doesn't need to be a link.

**Comment by bantic** [comment]
@sandersonet yeah, was just about to ask that. thanks :)

**Comment by bantic** [comment]
@sandersonet the current git ref would be the one matching app.currentImage.gitRef, right? Not app.lastDeployOperation.gitRef? (Or are they the same?)

**Comment by sandersonet** [comment]
You are correct, `app.currentImage.gitRef` is the correct ref.  Currently `app.lastDeployOperation` does not verify that the last deploy actually succeeded, so it's possible that Git ref isn't actually what's currently deployed.  We could probably add an icon or color indicator to show if that Last Deployed By was a success or failure.  (I can add that easily later on)
