### ISSUE TITLE
Stacks index page

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#92]
After some thought, I think having an actual stacks index page is a better UX than using a dropdown for stack switching.  

![205d stacks](https://cloud.githubusercontent.com/assets/884151/6236715/ddca5e38-b6ba-11e4-9f77-56a926fcf170.png)

**Comment by bantic** [comment]
@sandersonet Would the "Apps & Databases" link in the nav take on to this screen?

And would this become the default landing screen when a user signs in?

**Comment by sandersonet** [comment]
@bantic  I am actually working on this issue right now.  I'll have a PR soon.  

Apps & Databases is the default and will link to a new stacks.index route.
