### ISSUE TITLE
Update document page title on route transition

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#94]
- [x] Index => 'Aptible Dashboard'
- [x] Stack#show#apps => "${stack.handle} Apps - ${organization.name}"
- [x] Stack#show#apps#new => "Create an App - ${stack.handle}"
- [x] Stack#show#databases => "${stack.handle} Databases - ${organization.name}"
- [x] Stack#show#databases#new => "Create a Database - ${stack.handle}"
- [x] Stack#show#logging => "${stack.handle} Logging - ${organization.name}"
- [x] App#show => "${app.handle} - ${stack.handle}" (note: this route currently immediately transitions to App#show#services, so this title would never be seen)
- [x] App#show#services => "${app.handle} Services - ${stack.handle}"
- [x] App#show#domains => "${app.handle} Domains - ${stack.handle}"
- [x] App#show#domains#new => "Add a domain - ${app.handle} - ${stack.handle}"
- ~~[ ] App#show#domains#edit => "Edit ${domain.virtual_domain} - ${app.handle}"~~ (see #112)
- [x] App#show#activity => "${app.handle} Activity - ${stack.handle}"
- [x] App#show#deprovision => "Deprovision ${app.handle} - ${stack.handle}"
- [x] Database#show#activity => "${database.handle} Activity - ${stack.handle}"
- [x] Database#show#deprovision => "Deprovision ${database.handle} - ${stack.handle}"

**Comment by mixonic** [comment]
Assigning this to myself.
