### ISSUE TITLE
"Apps & Databases" link is broken from /settings page

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#96]
![image](https://cloud.githubusercontent.com/assets/2023/6237555/e9d67eda-b6c1-11e4-84dc-228999f2de21.png)

This will probably be addressed by work done to coalesce all stacks and organizations into a single dropdown selector.

**Comment by sandersonet** [comment]
This link is going to change in one of two ways:

- If the user has multiple stacks or multiple organizations, this will link to a new stacks#index route
- If the user has only a single stack, it should link directly to that stack

**Comment by bantic** [comment]
Yep, the link now goes to "/stacks". This bug is moot.
