### ISSUE TITLE
Routes don't fully transition when loading an empty model

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#97]
If you visit app#vhosts and the app currently has no vhosts, the route isn't fully loaded.  This leaves other items in the nav with the `ember-transitioning-out` class.  Ideally the route should fully resolve with a simple message like 'This app has no Domains.'

**Comment by bantic** [comment]
@sandersonet Can you give some more detail on this? I turned on `ENV.APP.LOG_TRANSITIONS` and `ENV.APP.LOG_TRANSITIONS_INTERNAL` in `config/environment.js` and they appear to report that the transition was completed.

I'm also checking for the `ember-transitioning-out` class but not finding it.

Here's what I see:
![image](https://cloud.githubusercontent.com/assets/2023/6255429/d69c0120-b77d-11e4-8968-2714507c3115.png)

To show a message that there are no domains, we can add 
```
{{else}}
This app has no domains
{{/each}}
```

To `app/app/vhosts/index/template.hbs` where the `{{/each}}` is now.

**Comment by sandersonet** [comment]
@bantic After looking at this more, it seems to only affect the activity tab.  If it's empty, it will leave other nav items with `ember-transitioning-out`.

**Comment by bantic** [comment]
Hmm, still having trouble reproducing this. I may sync up with you on it separately

**Comment by bantic** [comment]
@sandersonet assigning this one back to you — can you update or close after double-checking that you're running into it with ember 1.10?

**Comment by bantic** [comment]
@sandersonet giving this one a close — I believe it was limited to Ember 1.11 beta. If you run into it again please reopen!
